### ISSUE TITLE
дополнительный ввод даных через уарт с блютуз модуля. 

### ISSUE THREAD

**Issue by batbsv** [FreeJoy-Team/FreeJoyWiki#11]
сделайте возможность подключить блютуз модуль к уарту. идея- для телефона или планшета пишите свой софт с кнопочками, осями, красивыми шкурками. подключаетесь через блютуз телефона (планшета)  к модулю в джойстике, и пользуясь экраном плашета как дополнительным РУД и переключателем различных режимов.
я это у себя на ардуине промикро 32u4 пробую делать. скорость блютуз 115200. рабочий вариант написанный через 
mit appinventor 
![Screenshot_2020-11-30-20-11-33-710_edu mit appinventor aicompanion3](https://user-images.githubusercontent.com/2844001/100603832-038af680-3349-11eb-96b6-2cc8c42f7a80.jpg)
как познакомился со спрайтами начал переделывать интерфейс
![Screenshot_2020-11-30-20-13-28-827_edu mit appinventor aicompanion3](https://user-images.githubusercontent.com/2844001/100603947-33d29500-3349-11eb-9d03-5ed8a3706f16.jpg)
все элементы кликабельны и крутятся. но в mit appinventor  очень все запутанно ,а другого я не умею, пока забросил. надеюсь вы поняли мысль.  можно очень гибко на планшете-телефоне настраивать все горячие кнопки, выводить закладками определенные группы кнопок, для навигации, для режимов двигателя, просто подкидывая раскладку кнопок и осей. и по блютузу запускать в главный джойстик и он уже отправляет в компьютер . вместо  телефона можно соорудить дополнительный руд с блютуз модулем, со своими кнопками осями  и контроллером будет как в обычных джоях на две руки,но вместо кабеля будет блютуз. также можно через уарт вести отладку программы джойстика на лету. подставляя значения переменных и контолируя что джойстик отправляет в систему.а если ваш модуль может отпралять нажате кнопок клавиатуры, мыши и перемещения мыши, ваш проект станет очень гибким и всеобьемлющим. к слову 32u4 это все умеет. через дешевое составное усб устройство нажимает кнопки клавы, двигает мышь, но ,хотелось больше мошности . 
ЗЫ можно также использовать гироскоп телефона и акселерометр. я держал телефон на вытянутой руке и управлял самолетом крутя телефон.данные по блютузу шли в блютуз ардуинки, там оси х и у подменялись даными от гироскопов и отправлялись с ил-2.    это еще не все что можно придумать и реализовать. 
например хатка = mpu6050 прикрепленная на голове с радиоканалом по блютузу( track ir для бедных). ардуинка это не потянет,там фильтрацию надо осуществлять.ресурсов платки немного.

**Comment by batbsv** [comment]
собственно в микроконтроллер требуется ввести протокол для общения ядра с уартом. 
например "X=1024", "b1=on", "Y=32768","kbA=press" ,""kbA=release"
естественно не обязательно такие большие команды делать,это для примера.
пропусконй способности 115200 хватает чтобы плавно через уарт изменять положение оси,например газа,или триммеров, там не нужно огромное быстробействие.

**Comment by vostrenkov** [comment]
Добрый день!
Такая система вряд ли появится в рамках этого проекта в ближайшем будущем, так как помимо интеграции самого управления по UART и вписывания этого в текущую систему конфигурирования потребуется ещё разработать мобильное приложение, на что у команды сейчас нет компетенций

**Comment by batbsv** [comment]
но вы же можете сделать своеобразный API для основных функций- присвоение осям значений, нажатие или отпускание кнопок. просто интерфейсом бы выступал уарт. а приложение обязательно напишут энтузиазисты,когда распробуют удобность.

**Comment by vostrenkov** [comment]
Да, это возможно. В целом задача перекликается с задачей по подключению двух контроллеров друг к другу, только вместо второго контроллера здесь bluetooth модуль.
Я не могу обещать что этот функционал будет сделан скоро, так как есть другие приоритетные задачи, но какая-то возможность по UART получать и передавать данные вполне вероятно появится

**Comment by batbsv** [comment]
спасибо большое. подскажите, какое программное  обеспечение достаточно для компилирования выложенных исходников freejoy? достаточно ли демо версии сред разработки? пора уходить из ардуино на более серьезные среды.

**Comment by vostrenkov** [comment]
Я работаю в Keil uVision v5, с включенной оптимизацией код влезает в ограничение бесплатной версии. Можно собирать с gcc через makefile.
Кто-то помнится смог собрать в platform io одну из ранних версий, надо поискать по issues

**Comment by batbsv** [comment]
Sprint-Layout 6 не от крывает файлы MMJoy2_74HC165.lay6 TLE5011.lay6 и  т.д.  Вы в какой версии их делали?
на какртинках в инструкциях не понятны номиналы резисторов, только бледные красные прямоугольники. пожалуйста, добаляйте в тексе описания подключений  номиналы .
для светодиодных выводов можно использовать 16 канальные светодиодные драйвера STP16C596,MBI5026GF,MAX7219CNG,или сдвиговые регистры 74HC595.

**Comment by vostrenkov** [comment]
Платы *.lay6 в папке /3rd-party - это файлы плат для SprintLayout6, разработанные сторонними разработчиками (причем некоторые изначально под проект mmjoy). У вас, вероятно, просто переведенная на русский 5я версия SprintLayout, которой автор перевода сам назначил 6й номер. Вот информация по этому поводу:
https://radioskot.ru/forum/30-1282-1
Wiki - это тоже народное творчество, большинство контента в вики было добавлено туда сообществом, я по большей части занимаюсь только редактурой. Кстати, вы тоже вполне можете сделать pull-request в вики с более наглядными схемами подключения, и я добавлю их в основную ветку.
Сдвиговые регистры для светодиодов вероятно когда нибудь будут, давно хочу их добавить, но есть более важные вещи

**Comment by batbsv** [comment]
спасибо,  лайот подошел, микрухи я заказал для светодиодов. буду тестировать как придут.

**Comment by batbsv** [comment]
Это нормально что SPI_CLK  такой  " многоимпульсный" ? 
![Desktop Screenshot 2020 12 12 - 13 27 27 81](https://user-images.githubusercontent.com/2844001/101975363-66508c00-3c7f-11eb-8f72-89155a20c3a7.png)

**Comment by vostrenkov** [comment]
На такой развёртке особо непонятно. У вас тут видно не сам клок, а множество циклов опроса
