### ISSUE TITLE
Armgcc app firmware !Don't work

### ISSUE THREAD

**Issue by chuoique** [FreeJoy-Team/FreeJoyWiki#13]
I successful when try compiler on MDK-ARM vs arm gcc, but app's firmware run as image follow:
<img width="513" alt="freejoy_mdk_arm" src="https://user-images.githubusercontent.com/3771658/103498789-79b6d780-4e78-11eb-8fb8-952c2205cb06.png">
<img width="510" alt="freejoy_armgcc" src="https://user-images.githubusercontent.com/3771658/103498976-1da08300-4e79-11eb-905a-278a5aac48e4.png">

arm gcc boot firmware seem work good.
<img width="510" alt="freejoy_armgcc_boot" src="https://user-images.githubusercontent.com/3771658/103499414-8b997a00-4e7a-11eb-9c80-a90dc16823bd.png">

**Comment by vostrenkov** [comment]
Hi, 
both boot and app should be flashed to the MCU for proper work. Boot is flashed starting from 0x8000000 (starting point of program memory) and App is flashed with offset to 0x8002000.
Are you sure you flash your App to the right place?

**Comment by chuoique** [comment]
Thanks your repply,
I tried both that flashed with start adrress (boot+app same your comment) use ST-LINK Utility, OR that flashed first: boot use ST-LINK Utility, second: app use "Freejoy Configurator firmware flahser".
I guess, it maybe conflict in.. etc (armgcc's config, startup_stm32f10x_md.s, or on usb init..).

ps. I had modifier a little follow link: http://amitesh-singh.github.io/stm32/2017/05/27/Overcoming-wrong-pullup-in-blue-pill.html and change some startup file, but it didn't worked.

**Comment by chuoique** [comment]
Hi, I had update lastest version  gcc-arm-none-eabi at https://developer.arm.com . It run ok!. thanks you!
