### ISSUE TITLE
MLX90393 не реагирует на магнит.

### ISSUE THREAD

**Issue by batbsv** [FreeJoy-Team/FreeJoyWiki#14]
MLX90393 не реагирует на магнит, дорожку порезал как в инструкции ,куда копать?

![Desktop Screenshot 2021 01 14 - 22 08 55 97](https://user-images.githubusercontent.com/2844001/104595237-a4453380-56b5-11eb-8539-06605783f0af.png)

![Desktop Screenshot 2021 01 14 - 22 09 08 33](https://user-images.githubusercontent.com/2844001/104595263-aeffc880-56b5-11eb-9bcc-633504c3ece1.png)

судя по обмену,микросхема вроде живая. платка такая как в инструкции вики.

![Desktop Screenshot 2021 01 14 - 22 09 47 64](https://user-images.githubusercontent.com/2844001/104595328-ca6ad380-56b5-11eb-8c07-5266d3a177ed.png)

**Comment by vostrenkov** [comment]
Если можешь, постучись в дискорд Magners#1207. У меня усть пара бета версий, где возможно оно починено

**Comment by batbsv** [comment]
сожалению тебя не находит . я bat_bsv#9985

**Comment by michalsok** [comment]
I cant read Russian but I also have a problem connecting MLX90393
I did cut the CS trace, I did swap MOSI and MISO as picture and for my own sake confirmed with the datasheet that in fact this breakout board is mislabeled.
When I probe the SPI bus the commands do not make sense and the response (status byte) from MLX is 00010001 indicating error.
The first clock pulse looks suspicious and out of sync. Also, are you sending the commands (bytes) MSb first?
Were you ever able to test the MLX90393 successfully?
Please help.
Thank you,

Mike.
![MLX90393 SPI](https://user-images.githubusercontent.com/24321717/106008879-c495ca80-6085-11eb-825b-3ad92afc41dc.jpg)

**Comment by vostrenkov** [comment]
I confirm there possible errors with MLX90303 communication. It will be fixed in 1.7.0 version coning soon
