### ISSUE TITLE
ARCELI STM32F103C8T6

### ISSUE THREAD

**Issue by pipes80-collab** [FreeJoy-Team/FreeJoyWiki#15]
I have buy this product for convert my G29 pedals in usb, I hope that work fine.
My question is: can I use an added module ad1115 for improving resolution?
Thank for this great work

**Comment by vostrenkov** [comment]
YoU can use ADS1115 ADC to improve resolution but keep in mind that if you have noisy pots it won't help much.
FreeJoy internal ADC is good enough for pedals but you need to use good pots or other sensors

**Comment by pipes80-collab** [comment]
in fact in the future I thought of replacing them with other good potentiometers or even with the magnetic hall version. I thanks you for quick help
