### ISSUE TITLE
Wiki Led setup page - dead link

### ISSUE THREAD

**Issue by geologic** [FreeJoy-Team/FreeJoyWiki#23]
Hi

At your main wiki page, LED setup page points to a dead link:

https://github.com/FreeJoy-Team/FreeJoyWiki/blob/master/eng/LED-configuration.md -> not found
https://github.com/FreeJoy-Team/FreeJoyWiki/blob/master/eng/LED-connection.md -> correct link

**Comment by vostrenkov** [comment]
Thanks! fixed
