### ISSUE TITLE
Config file format import old config into updated device

### ISSUE THREAD

**Issue by AndyPeacock** [FreeJoy-Team/FreeJoyWiki#28]
I have a config I saved to file before I update my device to 1.7.0

I understand you now have to use FreeJoyConfiguratorQT with 1.7.0, but how do you migrate the config from an older version as the file formats do not seem to be compatible?

**Comment by Reksotiv** [comment]
use [configuratorQt for 1.6.2](https://github.com/FreeJoy-Team/FreeJoyConfiguratorQt/releases/tag/1.1.2) and save to file then update to 1.7

**Comment by AndyPeacock** [comment]
Sorry, that is so obvious, I should have tried that. Thanks for letting me know.
