### ISSUE TITLE
[Question]  74HC165 Shift Register PCB - Do I need 10 kOhm resistors ?

### ISSUE THREAD

**Issue by speedbird5** [FreeJoy-Team/FreeJoyWiki#39]
Hi,

Pls refer to this scheme https://github.com/FreeJoy-Team/FreeJoyWiki/blob/master/eng/Connecting-buttons-to-shift-registers.md

I intend to buy the PCB which you have shown, see image below.

https://github.com/FreeJoy-Team/FreeJoyWiki/blob/master/images/74hc165_pcb.jpg

My understanding is that the PCB board shown already has resistors on each input.

**_Using the PCB shown above_**, if I have ten 74HC165 shift registers connected together,  do I still need the 10 kOhm resistors?

If I do need them, how many 10 kOhm resistors do I need?  

Thanks.

**Comment by vostrenkov** [comment]
Hello,
this board have embedded pull up resistors, so you dont need to add extra resistors

**Comment by speedbird5** [comment]
Thanks Yury
