### ISSUE TITLE
Multiple joysticks in a single board

### ISSUE THREAD

**Issue by fedekrum** [FreeJoy-Team/FreeJoyWiki#43]
One question.
Is it possible to make one board appear as multiple joysticks?
The case is that I am building a 4 player arcade.
Each player uses 10 buttons (40) and I need 10 more buttons (coin, Select,Start ,one player, two players, etc...) and I would like to use only one USB port (like the Raspberry Pi Zero W2 has)
Thanks

**Comment by vostrenkov** [comment]
https://github.com/FreeJoy-Team/FreeJoy/issues/148
