### ISSUE TITLE
Diode before or after switch?

### ISSUE THREAD

**Issue by omwdunkley** [FreeJoy-Team/FreeJoyWiki#46]
Hello!

The wiring documentation examples for the _buttons_ and _encoders_ via a button matrix differ.

The button example uses 
`row - switch - diode (|<) - row`
and the encoder examples uses
`row - diode (|<) - switch - row`

Just wondering why the difference in the docs and if it matters!
Thank you:)

**Comment by vostrenkov** [comment]
Hi,
It doesn't matter before or after, only direction make sense. Diode works only when switch is closed and electrically there won't be "before" or "after"

**Comment by omwdunkley** [comment]
Perfect explanation, thanks!
