### ISSUE TITLE
Prescaller Axis

### ISSUE THREAD

**Issue by evgavr** [FreeJoy-Team/FreeJoyWiki#5]
Hello!
I am facing the problem of setting the axes.
When choosing Prescaler = for example 8% should I get a response of 8% (red bar) from 100% (green bar) to stick shift?
If so, I was unable to configure Prescaler or it doesn't work.
What am I doing wrong?

https://photos.app.goo.gl/QMo7pqF1ktY1U4rA9

**Comment by vostrenkov** [comment]
Hi there!
For now prescaler works as activated function so you should map an activation button for this:
![image](https://user-images.githubusercontent.com/21309063/88639132-1ce31400-d0c5-11ea-92fe-4429caf98139.png)

I will add possibility for prescaler work in permanent mode in the next release (it will come very soon) but as a workaround you can set for this a button in forever pressed state like single radiobutton:
![image](https://user-images.githubusercontent.com/21309063/88639593-9da21000-d0c5-11ea-9aae-324dbe0520ef.png)

So watch for the news and stay updated
