### ISSUE TITLE
Other STM32 micros?

### ISSUE THREAD

**Issue by virtual812** [FreeJoy-Team/FreeJoyWiki#7]
Hey there, love the project.
Just wondering if i were to build my own PCB are there other options with regard to STM32 choice?

The Controller-Lite looks like a good starting point, no need for the 32,768 Crystal etc...

Just got in the mail today one of these WeAct Black Pill V2.0
[https://stm32-base.org/boards/STM32F411CEU6-WeAct-Black-Pill-V2.0](url)

This is based on the STM32F411CEU6 and seems to have a 100MHz clock would this work?

**Comment by vostrenkov** [comment]
Hi,
this software targeted on STM32F103 MCU line and won't work with STM32F4 or any other. 
If you want to use F4 line you will have to port the code with many changes

**Comment by SarwarN88** [comment]
Hi,
I am using Maple mini that is based on STM32F103C8T6 which should work. I flashed the .hex file to my board using ST-Link v2. However, when I connect the device to my pc using usb it doesn't connect. It not even showing that a usb device is connected. Do I need to flash all the 3 files inside the FreeJoy_v1_6_2b3.zip?
