### ISSUE TITLE
not a problem but a comparison ads1115

### ISSUE THREAD

**Issue by pipes80-collab** [FreeJoy-Team/FreeJoyWiki#74]
good morning everyone, I would like to ask whoever connected it, the connection method of the ads1115, simply a photo is enough, thank you to anyone who will lend themselves to this request

**Comment by vostrenkov** [comment]
Have you already try this?
https://github.com/FreeJoy-Team/FreeJoyWiki/blob/master/eng/Connecting-analog-axes-to-ADS1115.md

**Comment by pipes80-collab** [comment]
yes, I followed that and understood it as a scheme, but my question was specific to how to connect them, whether via the PIN supplied together with the stm32 or via wire
