### ISSUE TITLE
On Linux  all buttons presses reported as Button 1

### ISSUE THREAD

**Issue by EpoxyRaisin** [FreeJoy-Team/FreeJoyWiki#9]
Freejoy with 12 Buttons works fine on windows device. But on Linux all axis and buttons are detected but any button press is reported as Button 1 press. I tested on Linux Mint PC and Raspberry with Retropie. Other gamepad controller works fine on both machines.

Any hints on that behaviour?

**Comment by vostrenkov** [comment]
Yes, 
probably it is because of some latest hid report changes. I will revert this changes soon:
[](https://photos.app.goo.gl/Xo1F5wyPfW4htFsm8)
